AWSTemplatFormatVersion: "2010-09-09"

Description: Test instance and security group

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-052efd3df9dad4825
      InstanceType: t3.micro
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

